// <auto-generated />
using System;
using BoyutAplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoyutAplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BoyutAplication.Entities.InvoiceStatusLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("INVOICE_NUMBER");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("REQUEST_TIME");

                    b.Property<string>("ResponseCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RESPONSE_CODE");

                    b.Property<string>("ResponseMessage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RESPONSE_MESSAGE");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TAX_NUMBER");

                    b.HasKey("Id");

                    b.ToTable("INVOICE_STATUS_LOG", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
